[package]
name = "xi-tui"
version = "0.1.0"
authors = ["Corentin Henry <corentinhenry@gmail.com>"]

[features]
yaml = []
yaml_format = []

[dependencies]
clippy = "*"
termion = "*"
jsonrpc-core = "*"
clipboard = "0.1.2"
serde_json = "*"
log = "0.3"
unicode-width = "0.1.3"

[dependencies.log4rs]
features = ["yaml"]
